### ISSUE TITLE
How to pass parameters with docker-compose

### ISSUE THREAD

**Issue by jim256** [u1234x1234/torpool#2]
Is there a way to pass the following arguments when including this in a docker-compose.yml ?

NewCircuitPeriod
MaxCircuitDirtiness
Tors

I've tried a few different things ('environment:' in docker-compose.yml, passing args to a dockerfile, etc.) but it doesn't seem to pick up the values.

**Comment by jim256** [comment]
Actually got it partially going with this in my docker-compose:
```

    haproxy:
        image: u1234x1234/torpool:1.0.2
        command: ['--Tors=25']
        container_name: haproxy-container
        ports:
            - "9200:9200"
            - "9300:9300"
            - "9500:9500"
```

But I'd also like to be able to rotate by passing --MaxCircuitDirtiness 30 and --MaxCircuitDirtiness 30 --NewCircuitPeriod 30

I usually pass those when using docker run, but can't figure out how to pass them with docker-compose. With other images, I've just included multiple comma-separated args in the command field. If I add these here, I get something like "Command-line option '-MaxCircuitDirtiness 30' with no value. Failing." (depending on if I use one dash or two and if I use a space or equals operator.

Thoughts?

**Comment by u1234x1234** [comment]
Hello, Jared

Sorry for the inconvenience. Seems it is caused by how the argument parsing is handled.

Working example:
```yaml
version: '3'
services:
  haproxy:
    image: u1234x1234/torpool:1.0.2
    command: ['--Tors', '2', '--NewCircuitPeriod', '30', '--MaxCircuitDirtiness', '30']
    container_name: haproxy-container
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9500:9500"
```
Does this solve your problem?
